version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    build: ./web
    command: yarn start
    volumes:
      - ./web:/web
    ports:
      - 3000:3000

  api:
    build: ./api
    command: air
    volumes:
      - ./api:/api
    ports:
      - 8080:8080
    depends_on:
      - db
