version: '3'

services:
  db:
    image: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    build: ./web
    command: yarn start
    volumes:
      - ./web:/web
    ports:
      - 3000:3000

  api:
    build: ./api
    volumes:
      - ./api:/api
    depends_on:
      - db
