// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Content string `json:"content"`
}

type UpdateTodoInput struct {
	Content string `json:"content"`
}
